table MeasureTable
	lineageTag: b7fa9939-8818-4a0c-bbd0-f5a20a32cf53

	measure UserLogin = USERNAME()
		lineageTag: 72e1bbfa-024d-42c8-867c-99a44719a656

	column Column1
		dataType: int64
		formatString: 0
		lineageTag: 9bb0f23a-cfd7-4bdf-9071-218c190dd118
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition MeasureTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

