CREATE TABLE [Apple_data_silver].[Apple_sil_data] (

	[sale_id] varchar(8000) NULL, 
	[sale_date] date NULL, 
	[year] int NULL, 
	[quarter] varchar(8000) NULL, 
	[month] varchar(8000) NULL, 
	[country] varchar(8000) NULL, 
	[region] varchar(8000) NULL, 
	[city] varchar(8000) NULL, 
	[product_name] varchar(8000) NULL, 
	[category] varchar(8000) NULL, 
	[storage] varchar(8000) NULL, 
	[color] varchar(8000) NULL, 
	[unit_price_usd] float NULL, 
	[discount_pct] int NULL, 
	[units_sold] int NULL, 
	[discounted_price_usd] float NULL, 
	[revenue_usd] float NULL, 
	[currency] varchar(8000) NULL, 
	[fx_rate_to_usd] float NULL, 
	[revenue_local_currency] float NULL, 
	[sales_channel] varchar(8000) NULL, 
	[payment_method] varchar(8000) NULL, 
	[customer_segment] varchar(8000) NULL, 
	[customer_age_group] varchar(8000) NULL, 
	[previous_device_os] varchar(8000) NULL, 
	[customer_rating] float NULL, 
	[return_status] varchar(8000) NULL, 
	[__filepath__] varchar(8000) NULL, 
	[year_month] varchar(8000) NULL
);